# Application
spring.application.name=energy-grid-composition-service

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/energy_grid
spring.datasource.username=postgres
spring.datasource.password=271025

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
server.address=0.0.0.0